#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running all tests before pushing 🚀"
yarn build || 
(
  echo "❌ Next Js Build Failed"
  false;
)

cd server && yarn build || 
(
  echo "❌ Server Build Failed"
  false;
)

echo "✅ Build successful"