name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      run: cd server && yarn install --frozen-lockfile

    - name: Build the app
      run: cd server && yarn build

    - name: Archive production artifact
      working-directory: server
      run: tar -czf dist.tar.gz dist

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist.tar.gz
